version: '3.1'

services:
 rabbitmq:
   image: rabbitmq:management
   restart: no
   environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
   ports:
     - "5672:5672"
     - "15672:15672"

